live_config_reload = true
"window.opacity" = 1.0

[colors.bright]
black = "#505050"
blue = "#6c99ba"
cyan = "#7dd5cf"
green = "#b8bb26"
magenta = "#9e4e85"
red = "#ac4142"
white = "#f5f5f5"
yellow = "#e5b566"

[colors.cursor]
cursor = "#d0d0d0"

[colors.normal]
black = "#1d1f21"
blue = "#6c99ba"
cyan = "#7dd5cf"
green = "#b8bb26"
magenta = "#9e4e85"
red = "#ac4142"
white = "#d0d0d0"
yellow = "#e5b566"

[colors.primary]
background = "#202020"
foreground = "#d0d0d0"

[env]
TERM = "xterm-256color"

[font]
draw_bold_text_with_bright_colors = true
ligatures = true
size = 19

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 8

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "SemiLight"

[font.offset]
x = 0
y = 14

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt|Option"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt|Option"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 4
y = 0
