#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="Geist Mono"

bar=(
  position=top
  height=32
  blur_radius=30
  padding_left=10
  padding_right=20
  color=$Crust
)

default=(
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:14.0"
  background.color=$Crust
  background.corner_radius=5
  background.height=18
  icon.color=$Lavender
  label.color=$Text
  icon.y_offset=1
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)

sketchybar --default "${default[@]}" --bar "${bar[@]}" 

# Left side items
source $ITEM_DIR/workspaces.sh

# Right side items

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/ssd.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
