# vim:ft=kitty


map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+10 goto_tab 10
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+10 goto_tab 10

map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 7
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9
map ctrl+a>10 goto_tab 10

map cmd+w close_window_with_confirmation

map cmd+shift+p command_palette

map ctrl+shift+t new_tab_with_cwd
map cmd+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd

# Sessions
map ctrl+a>p goto_session -1
map ctrl+a>q goto_session $HOME/.config/kitty/sessions/finaipro.session
map ctrl+a>w goto_session $HOME/.config/kitty/sessions/sergio.session
map ctrl+a>e goto_session $HOME/.config/kitty/sessions/conectea-web.session
map ctrl+a>r goto_session $HOME/.config/kitty/sessions/conectea-jea.session
map ctrl+a>, goto_session $HOME/.config/kitty/sessions/dotfiles.session
map ctrl+a>n goto_session $HOME/.config/kitty/sessions/nvim.session
map ctrl+a>s launch --type=overlay /run/current-system/sw/bin/fish -c /Users/camilo/.config/kitty/scripts/list-sessions.sh
map ctrl+a>ctrl+k launch --type=overlay /run/current-system/sw/bin/fish -c /Users/camilo/.config/kitty/scripts/kill-active-sessions.sh
map ctrl+a>ctrl+s launch --type=overlay /run/current-system/sw/bin/fish -c /Users/camilo/.config/kitty/scripts/list-active-sessions.sh
# map ctrl+a>s goto_session


map ctrl+a>c new_tab_with_cwd
map ctrl+a>h neighboring_window left
map ctrl+a>j neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>l neighboring_window right
map ctrl+a>z toggle_layout stack
map ctrl+a>x close_window_with_confirmation
map ctrl+a>% launch --location=vsplit --cwd=current
map ctrl+a>" launch --location=hsplit --cwd=current
